return {
  kind = {
    -- based on lsp-kind
    Text = '',
    Method = '',
    Function = '',
    Constructor = '',
    Field = 'ﰠ',
    Variable = '',
    Class = 'ﴯ',
    Interface = '',
    Module = '',
    Property = 'ﰠ',
    Unit = '塞',
    Value = '',
    Enum = '',
    Keyword = '',
    -- Snippet = "",
    Snippet = '',
    Color = '',
    File = '',
    Reference = '',
    Folder = '',
    EnumMember = '',
    Constant = '',
    Struct = 'פּ',
    Event = '',
    Operator = '',
    TypeParameter = ''
  },
  type = {
    Array = '',
    Number = '',
    String = '',
    Boolean = '蘒',
    Object = '',
  },
  documents = {
    File = '',
    Files = '',
    Folder = '',
    OpenFolder = '',
  },
  git = {
    Add = '',
    Mod = '',
    Remove = '',
    Ignore = '',
    Rename = '',
    Diff = '',
    Repo = '',
    Octoface = '',

    Branch = '',
    Ahead = '⇡',
    Behind = '⇣',
  },
  ui = {
    ArrowClosed = '',
    ArrowOpen = '',
    Lock = '',
    Circle = '',
    BigCircle = '',
    BigUnfilledCircle = '',
    Close = '',
    NewFile = '',
    Search = '',
    Lightbulb = '',
    Project = '',
    Dashboard = '',
    History = '',
    Comment = '',
    Bug = '',
    Code = '',
    Telescope = '',
    Gear = '',
    Package = '',
    List = '',
    SignIn = '',
    SignOut = '',
    Check = '',
    Fire = '',
    Note = '',
    BookMark = '',
    Pencil = '',
    -- ChevronRight = "",
    ChevronRight = '>',
    Table = '',
    Calendar = '',
    CloudDownload = '',
  },
  diagnostics = {
    Error = '',
    Warning = '',
    Information = '',
    Question = '',
    Hint = '',
  },
  misc = {
    Robot = 'ﮧ',
    Squirrel = '',
    Tag = '',
    Watch = '',
    Smiley = 'ﲃ',
    Package = '',
    CircuitBoard = '',
  },
}
