return {
  -- {
  --   "vhyrro/luarocks.nvim",
  --   branch = "more-fixes",
  --   config = function()
  --     require("luarocks").setup({})
  --   end,
  -- },
  -- {
  --   "nvim-neorg/neorg",
  --   branch = "luarocks",
  --   enabled = false,
  --   dependencies = { "luarocks.nvim" },
  --   config = function()
  --     require("neorg").setup({
  --       load = {
  --         ["core.defaults"] = {},
  --       }
  --     })
  --   end,
  -- }
}
