return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
      {
        "nvim-treesitter/nvim-treesitter-context",
        opts = {
          enable = true,
          max_lines = 3,
          trim_scope = "inner",
          min_window_height = 20,
          patterns = {
            lua = {
              "table_constructor",
            },
          },
          zindex = 20,
          mode = "cursor",
        },
      },
    },
    main = "nvim-treesitter.configs",
    ---@type TSConfig
    opts = {
      ensure_installed = {
        "arduino",
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        -- 'comment',
        "cpp",
        "css",
        "dart",
        "diff",
        "dockerfile",
        "fish",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "graphql",
        "html",
        "http",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "kotlin",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "meson",
        "ninja",
        "nix",
        -- "norg",
        "org",
        "prisma",
        "pug",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "scheme",
        "scss",
        "sql",
        "svelte",
        "swift",
        "teal",
        "toml",
        "tsx",
        "typescript",
        "vhs",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
        "zig",
      },
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      indent = { enable = true },
      playground = { enable = true },
    },
  },
  { "nvim-treesitter/playground", cmd = "TSPlaygroundToggle" },
}
